// Generated by CoffeeScript 1.7.1
(function() {
  $(document).ready(function() {
    return $("#refresh_button").on("click", function(ev) {
      return $.get(Django.url("api:random_log_message"), {
        format_id: $(this).attr("data-formatid")
      }, function(response) {
        return $("#id_input").val(response);
      });
    });
  });

}).call(this);

//# sourceMappingURL=test_format.map
