// Generated by CoffeeScript 1.7.1
(function() {
  var global_message_rates, gotWebSocketConnection, num, updateMessageSpeedGraph;

  global_message_rates = (function() {
    var _i, _results;
    _results = [];
    for (num = _i = 0; _i <= 29; num = ++_i) {
      _results.push(0);
    }
    return _results;
  })();

  console.log(global_message_rates);

  $(document).ready(function() {
    return ab.connect("ws://localhost:6062", gotWebSocketConnection, function(code, reason) {
      return console.log("Error connecting to WebSockets: " + reason);
    });
  });

  gotWebSocketConnection = function(session) {
    console.log("Subscribed");
    return session.subscribe("logbook/stat/got_log_line", function(uri, event) {
      $("#messages_per_sec").text(event);
      return updateMessageSpeedGraph(event);
    }, function(error, desc) {
      return console.log("Error: " + error + " Desc: " + desc);
    });
  };

  updateMessageSpeedGraph = function(message_rate) {
    global_message_rates.push(message_rate);
    if (global_message_rates.length > 30) {
      global_message_rates = global_message_rates.slice(1, 31);
    }
    console.log(global_message_rates);
    return $("#message_rate_graph").sparkline(global_message_rates);
  };

}).call(this);

//# sourceMappingURL=dashboard.map
